### PR TITLE
2016556035 ERDAL KAMA

### PR DESCRIPTION
**Pull request by erdalkama**

### CODE REVIEW

**Review by erdalkama — COMMENTED** [review]
OUTPUT

**Comment by erdalkama** [comment]
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <time.h>


void Swap(int *xp, int *yp)
{
	int temp = *xp;
	*xp = *yp;
	*yp = temp;
}


void SwapChar(char *xp, char *yp)
{
	char temp = *xp;
	*xp = *yp;
	*yp = temp;
}


void Merge(int arr[], int l, int m, int r)
{
	int i, j, k, x1, x2;
	x1 = m - l + 1;
	x2 = r - m;

	int L[x1], R[x2];

	for (i = 0; i < x1; i++)
		L[i] = arr[l + i];
	for (j = 0; j < x2; j++)
		R[j] = arr[m + 1 + j];

	i = 0;
	j = 0;
	k = l;

	while (i < x1 && j < x2) {
		if (L[i] <= R[j]) {
			arr[k] = L[i];
			i++;
		}
		else {
			arr[k] = R[j];
			j++;
		}
		k++;
	}

	while (i < x1) {
		arr[k] = L[i];
		i++;
		k++;
	}

	while (j < x2) {
		arr[k] = R[j];
		j++;
		k++;
	}
}


void MergeSort(int arr[], int l, int r)
{
	if (l < r) {
		int m = l + (r - l) / 2;

		MergeSort(arr, l, m);
		MergeSort(arr, m + 1, r);

		Merge(arr, l, m, r);
	}
}


void MergeChar(char arr[], int l, int m, int r)
{
	int i, j, k, x1, x2;
	x1 = m - l + 1;
	x2 = r - m;

	int L[x1], R[x2];

	for (i = 0; i < x1; i++)
		L[i] = arr[l + i];
	for (j = 0; j < x2; j++)
		R[j] = arr[m + 1 + j];

	i = 0;
	j = 0;
	k = l;

	while (i < x1 && j < x2) {
		if (L[i] <= R[j]) {
			arr[k] = L[i];
			i++;
		}
		else {
			arr[k] = R[j];
			j++;
		}
		k++;
	}

	while (i < x1) {
		arr[k] = L[i];
		i++;
		k++;
	}

	while (j < x2) {
		arr[k] = R[j];
		j++;
		k++;
	}
}


void MergeSortChar(char arr[], int l, int r)
{
	if (l < r) {
		int m = l + (r - l) / 2;

		MergeSortChar(arr, l, m);
		MergeSortChar(arr, m + 1, r);

		MergeChar(arr, l, m, r);
	}
}


void BubbleSort(int arr[], int n)
{
	int i, j;
	for (i = 0; i < n - 1; i++)
		for (j = 0; j < n - i - 1; j++)
			if (arr[j] > arr[j + 1])
				Swap(&arr[j], &arr[j + 1]);
}

void BubbleSortChar(char arr[], int n)
{
	int i, j;
	for (i = 0; i < n - 1; i++)
		for (j = 0; j < n - i - 1; j++)
			if (arr[j] > arr[j + 1])
				SwapChar(&arr[j], &arr[j + 1]);
}


void InsertionSort(int arr[], int n)
{
	int i, x, j;
	for (i = 1; i < n; i++) {
		x = arr[i];
		j = i - 1;
		while (j >= 0 && arr[j] > x) {
			arr[j + 1] = arr[j];
			j = j - 1;
		}
		arr[j + 1] = x;
	}
}


void InsertionSortChar(char arr[], int n)
{
	int i, j;
	char x;
	for (i = 1; i < n; i++) {
		x = arr[i];
		j = i - 1;
		while (j >= 0 && arr[j] > x) {
			arr[j + 1] = arr[j];
			j = j - 1;
		}
		arr[j + 1] = x;
	}
}


void SelectionSort(int arr[], int n)
{
	int i, j, min;
	for (i = 0; i < n - 1; i++)
	{
		min = i;
		for (j = i + 1; j < n; j++)
			if (arr[j] < arr[min])
				min = j;
		Swap(&arr[min], &arr[i]);
	}
}


void SelectionSortChar(char arr[], int n)
{
	int i, j;
	char min;
	for (i = 0; i < n - 1; i++)
	{
		min = i;
		for (j = i + 1; j < n; j++)
			if (arr[j] < arr[min])
				min = j;
		SwapChar(&arr[min], &arr[i]);
	}
}


void PrintArray(int arr[], int n)
{
	int i;
	for (i = 0; i < n; i++)
		printf("%d ", arr[i]);
	printf("\n");
}


int main() {

	printf("------------ERDAL KAMA 2016556035------------\n");


	int number[] = { 2,0,1,6,5,5,6,0,3,5 };


	clock_t t;


	char name[] = "ERDAL KAMA";


	int n = sizeof(number) / sizeof(number[0]);


	int charSize = strlen(name);


	t = clock();


	printf("------------INSERTION SORT------------\n");


	InsertionSort(number, n);


	t = clock() - t;


	PrintArray(number, n);


	printf("Insertion Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	InsertionSortChar(name, charSize);


	t = clock() - t;


	printf("%s\n", name);


	printf("Insertion Char Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	int numX[] = { 2,0,1,6,5,5,6,0,3,5 };


	char nameX[] = "ERDAL KAMA";


	int x1 = sizeof(numX) / sizeof(numX[0]);


	int charSizeX = strlen(nameX);


	printf("------------SELECTION SORT------------\n");


	SelectionSort(numX, x1);


	t = clock() - t;


	PrintArray(numX, x1);


	printf("Selection Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	SelectionSortChar(nameX, charSizeX);


	t = clock() - t;


	printf("%s\n", nameX);


	printf("Selection Char Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	int numY[] = { 2, 0, 1, 6, 5, 5, 6, 0, 3, 5 };


	char nameY[] = "ERDAL KAMA";


	int nY = sizeof(numY) / sizeof(numY[0]);


	int charSizeY = strlen(nameY);


	printf("------------BUBBLE SORT------------\n");


	BubbleSort(numY, nY);


	t = clock() - t;


	PrintArray(numY, nY);


	printf("Bubble Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	BubbleSortChar(nameY, charSizeY);


	t = clock() - t;


	printf("%s\n", nameY);


	printf("Bubble Char Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	int numZ[] = { 2, 0, 1, 6, 5, 5, 6, 0, 3, 5 };


	char nameZ[] = "ERDAL KAMA";


	int nZ = sizeof(numZ) / sizeof(numZ[0]);


	int charSizeZ = strlen(nameZ);


	printf("------------MERGE SORT------------\n");


	MergeSort(numZ, 0, nZ - 1);


	t = clock() - t;


	PrintArray(numZ, nZ);


	printf("Merge Sort Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);


	MergeSortChar(nameZ, 0, charSizeZ - 1);


	t = clock() - t;


	printf("%s\n", nameZ);


	printf("Merge Sort Char Time: %lf\n", ((double)t) / CLOCKS_PER_SEC);



	return 0;
}

**Comment by abbaselmas** [comment]
Sorting klasörü altına yeni bir klasör açıp içerisine C dosyasını ve ekran görüntüsünü koymalıydın. Zaten geç göndermişsin.

**Comment by erdalkama** [comment]
HATA
Hocam saatlerdir uğraşıyorum yüklemek için daha önce githup kullandım ama 403 numaralı hatayı bir türlü çözemedim. Ben de bu şekilde bir çözüm düşünmüştüm.

**Comment by erdalkama** [comment]
Hocam saat 16'dan beri yüklemeye çalışıyorum. Hep son adımda hata veriyor. Arkadaşların Github masaüstü uygulaması metodunu da denedim ancak sonuç farksız farklı bir bilgisayarım olmadığı için deneme yapamadım. Nasıl yükleyebilirim hocam? Teşekkürler.
________________________________
Gönderen: Abbas Elmas <notifications@github.com>
Gönderildi: 27 Ekim 2020 Salı 18:12
Kime: abbaselmas/cen215DataStructureLab <cen215DataStructureLab@noreply.github.com>
Bilgi: erdalkama <erdalkama@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [abbaselmas/cen215DataStructureLab] 2016556035 ERDAL KAMA (#230)


Sorting klasörü altına yeni bir klasör açıp içerisine C dosyasını ve ekran görüntüsünü koymalıydın. Zaten geç göndermişsin.

**Comment by abbaselmas** [comment]
benim repoma yüklemeye çalışıyormuşsun. unable to access gayet açıklayıcı bir hata aslında.
repomu forklayıp kendi forkunu güncelleyip bana PR gönderecektin kendi forkundan.

**Comment by erdalkama** [comment]
Teşekkür ederim hocam.

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Abbas Elmas<mailto:notifications@github.com>
Gönderilme: 27 Ekim 2020 Salı 18:40
Kime: abbaselmas/cen215DataStructureLab<mailto:cen215DataStructureLab@noreply.github.com>
Bilgi: erdalkama<mailto:erdalkama@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [abbaselmas/cen215DataStructureLab] 2016556035 ERDAL KAMA (#230)


benim repoma yüklemeye çalışıyormuşsun. unable to access gayet açıklayıcı bir hata aslında.
repomu forklayıp kendi forkunu güncelleyip bana PR gönderecektin kendi forkundan.

**Pull request closed without merging**
